# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup git user
        run: |
          git config --local user.email "57953088+juusoautiosalo@users.noreply.github.com"
          git config --local user.name "twinbase-file-modifier-workflow[bot]"
        
      - name: Check git status
        run: git status

      - name: Add twinbase/twinbase as a remote
        run: git remote add template https://github.com/twinbase/twinbase.git
        
      - name: Fetch main branch of the twinbase repo
        run: git fetch template
        
      - name: Show base yaml file
        run: cat docs/index.yaml
        
      - name: Check git status
        run: git status
        
      - name: Merge the remote template
        run: git merge template/main --allow-unrelated-histories
        continue-on-error: true
        
      - name: Show base yaml file
        run: cat docs/index.yaml
        
      - name: Check git status
        run: git status
        
      - name: Use files in the local repo
        run: git checkout --ours .
        
      - name: Show base yaml file
        run: cat docs/index.yaml
        
      - name: Check git status again
        run: git status
        
      - name: Add files to resolve merge conflict
        run: git add -u
        
      - name: Commit files
        run: git commit -m "Update Merge twinbase/twinbase"
        
      - name: Check git status
        run: git status
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      # Runs a set of commands using the runners shell
      - name: Congratulate
        run: |
          echo Congratulations!
          echo Your Twinbase may have been updated!
